branch-defaults:
  master:
    environment: rubyPumaTake2-env
global:
  application_name: ruby-puma-take2
  default_ec2_keyname: jeremypj-key-pair
  default_platform: 64bit Amazon Linux 2014.03 v1.1.0 running Ruby 2.0 (Puma)
  default_region: us-west-2
  profile: null
  sc: git
